"""PGA Tour stat ID lookup table."""
import pandas as pd

STAT_IDS = pd.DataFrame([
    # Strokes Gained
    {"stat_id": "02675", "stat_name": "SG: Total", "category": "Strokes Gained", "subcategory": "Strokes Gained Leaders"},
    {"stat_id": "02674", "stat_name": "SG: Tee-to-Green", "category": "Strokes Gained", "subcategory": "Strokes Gained Leaders"},
    {"stat_id": "02567", "stat_name": "SG: Off-the-Tee", "category": "Strokes Gained", "subcategory": "Strokes Gained Leaders"},
    {"stat_id": "02568", "stat_name": "SG: Approach the Green", "category": "Strokes Gained", "subcategory": "Strokes Gained Leaders"},
    {"stat_id": "02569", "stat_name": "SG: Around-the-Green", "category": "Strokes Gained", "subcategory": "Strokes Gained Leaders"},
    {"stat_id": "02564", "stat_name": "SG: Putting", "category": "Strokes Gained", "subcategory": "Strokes Gained Leaders"},
    # Off the Tee - Driving Leaders
    {"stat_id": "129", "stat_name": "Total Driving", "category": "Off The Tee", "subcategory": "Driving Leaders"},
    {"stat_id": "101", "stat_name": "Driving Distance", "category": "Off The Tee", "subcategory": "Driving Distance"},
    {"stat_id": "102", "stat_name": "Driving Accuracy Percentage", "category": "Off The Tee", "subcategory": "Accuracy"},
    {"stat_id": "02402", "stat_name": "Ball Speed", "category": "Off The Tee", "subcategory": "Radar"},
    # Distance (All Drives)
    {"stat_id": "159", "stat_name": "Longest Drives", "category": "Off The Tee", "subcategory": "Distance (All Drives)"},
    {"stat_id": "496", "stat_name": "Driving Pct. 320+ (Measured)", "category": "Off The Tee", "subcategory": "Distance (Measured)"},
    {"stat_id": "495", "stat_name": "Driving Pct. 300-320 (Measured)", "category": "Off The Tee", "subcategory": "Distance (Measured)"},
    {"stat_id": "454", "stat_name": "Driving Pct. 300+ (Measured)", "category": "Off The Tee", "subcategory": "Distance (Measured)"},
    {"stat_id": "455", "stat_name": "Driving Pct. 280-300 (Measured)", "category": "Off The Tee", "subcategory": "Distance (Measured)"},
    {"stat_id": "456", "stat_name": "Driving Pct. 260-280 (Measured)", "category": "Off The Tee", "subcategory": "Distance (Measured)"},
    {"stat_id": "457", "stat_name": "Driving Pct. 240-260 (Measured)", "category": "Off The Tee", "subcategory": "Distance (Measured)"},
    {"stat_id": "458", "stat_name": "Driving Pct. <= 240 (Measured)", "category": "Off The Tee", "subcategory": "Distance (Measured)"},
    {"stat_id": "317", "stat_name": "Driving Distance - All Drives", "category": "Off The Tee", "subcategory": "Distance (All Drives)"},
    {"stat_id": "02433", "stat_name": "Driving Pct. 320+ (All Drives)", "category": "Off The Tee", "subcategory": "Distance (All Drives)"},
    {"stat_id": "02432", "stat_name": "Driving Pct. 300-320 (All Drives)", "category": "Off The Tee", "subcategory": "Distance (All Drives)"},
    {"stat_id": "214", "stat_name": "Driving Pct. 300+ (All Drives)", "category": "Off The Tee", "subcategory": "Distance (All Drives)"},
    {"stat_id": "215", "stat_name": "Driving Pct. 280-300 (All Drives)", "category": "Off The Tee", "subcategory": "Distance (All Drives)"},
    {"stat_id": "216", "stat_name": "Driving Pct. 260-280 (All Drives)", "category": "Off The Tee", "subcategory": "Distance (All Drives)"},
    {"stat_id": "217", "stat_name": "Driving Pct. 240-260 (All Drives)", "category": "Off The Tee", "subcategory": "Distance (All Drives)"},
    {"stat_id": "218", "stat_name": "Driving Pct. <= 240 (All Drives)", "category": "Off The Tee", "subcategory": "Distance (All Drives)"},
    {"stat_id": "02341", "stat_name": "Percentage of Yardage covered by Tee Shots", "category": "Off The Tee", "subcategory": "Distance (All Drives)"},
    {"stat_id": "02342", "stat_name": "Pct. of Yardage by Tee Shots - Par 4s", "category": "Off The Tee", "subcategory": "Distance (All Drives)"},
    {"stat_id": "02343", "stat_name": "Pct. of Yardage by Tee Shots - Par 5s", "category": "Off The Tee", "subcategory": "Distance (All Drives)"},
    # Accuracy
    {"stat_id": "02435", "stat_name": "Rough Tendency", "category": "Off The Tee", "subcategory": "Accuracy"},
    {"stat_id": "459", "stat_name": "Left Rough Tendency", "category": "Off The Tee", "subcategory": "Accuracy"},
    {"stat_id": "460", "stat_name": "Right Rough Tendency", "category": "Off The Tee", "subcategory": "Accuracy"},
    {"stat_id": "080", "stat_name": "Right Rough Tendency (RTP Score)", "category": "Off The Tee", "subcategory": "Accuracy"},
    {"stat_id": "081", "stat_name": "Left Rough Tendency (RTP Score)", "category": "Off The Tee", "subcategory": "Accuracy"},
    {"stat_id": "01008", "stat_name": "Fairway Bunker Tendency", "category": "Off The Tee", "subcategory": "Accuracy"},
    {"stat_id": "461", "stat_name": "Missed Fairway Percent - Other", "category": "Off The Tee", "subcategory": "Accuracy"},
    {"stat_id": "213", "stat_name": "Hit Fairway Percentage", "category": "Off The Tee", "subcategory": "Accuracy"},
    {"stat_id": "02420", "stat_name": "Distance from Edge of Fairway", "category": "Off The Tee", "subcategory": "Accuracy"},
    {"stat_id": "02421", "stat_name": "Distance from Center of Fairway", "category": "Off The Tee", "subcategory": "Accuracy"},
    {"stat_id": "02422", "stat_name": "Left Tendency", "category": "Off The Tee", "subcategory": "Accuracy"},
    {"stat_id": "02423", "stat_name": "Right Tendency", "category": "Off The Tee", "subcategory": "Accuracy"},
    {"stat_id": "02438", "stat_name": "Good Drive Percentage", "category": "Off The Tee", "subcategory": "Accuracy"},
    # Radar
    {"stat_id": "02401", "stat_name": "Club Head Speed", "category": "Off The Tee", "subcategory": "Radar"},
    {"stat_id": "02403", "stat_name": "Smash Factor", "category": "Off The Tee", "subcategory": "Radar"},
    {"stat_id": "02404", "stat_name": "Launch Angle", "category": "Off The Tee", "subcategory": "Radar"},
    {"stat_id": "02405", "stat_name": "Spin Rate", "category": "Off The Tee", "subcategory": "Radar"},
    {"stat_id": "02406", "stat_name": "Distance to Apex", "category": "Off The Tee", "subcategory": "Radar"},
    {"stat_id": "02407", "stat_name": "Apex Height", "category": "Off The Tee", "subcategory": "Radar"},
    {"stat_id": "02408", "stat_name": "Hang Time", "category": "Off The Tee", "subcategory": "Radar"},
    {"stat_id": "02409", "stat_name": "Carry Distance", "category": "Off The Tee", "subcategory": "Radar"},
    {"stat_id": "02410", "stat_name": "Carry Efficiency", "category": "Off The Tee", "subcategory": "Radar"},
    {"stat_id": "02411", "stat_name": "Total Distance Efficiency", "category": "Off The Tee", "subcategory": "Radar"},
    {"stat_id": "02412", "stat_name": "Total Driving Efficiency", "category": "Off The Tee", "subcategory": "Radar"},
    # Approach the Green
    {"stat_id": "158", "stat_name": "Ball Striking", "category": "Approach the Green", "subcategory": "Approach Leaders"},
    {"stat_id": "103", "stat_name": "Greens in Regulation Percentage", "category": "Approach the Green", "subcategory": "GIR"},
    {"stat_id": "331", "stat_name": "Proximity to Hole", "category": "Approach the Green", "subcategory": "Accuracy from Fairway"},
    {"stat_id": "02331", "stat_name": "Approaches from > 100 yards", "category": "Approach the Green", "subcategory": "Approach Leaders"},
    {"stat_id": "02329", "stat_name": "Approaches from inside 100 yards", "category": "Approach the Green", "subcategory": "Approach Leaders"},
    {"stat_id": "02437", "stat_name": "Greens or Fringe in Regulation", "category": "Approach the Green", "subcategory": "GIR"},
    {"stat_id": "326", "stat_name": "GIR Percentage - 200+ yards", "category": "Approach the Green", "subcategory": "GIR"},
    {"stat_id": "327", "stat_name": "GIR Percentage - 175-200 yards", "category": "Approach the Green", "subcategory": "GIR"},
    {"stat_id": "328", "stat_name": "GIR Percentage - 150-175 yards", "category": "Approach the Green", "subcategory": "GIR"},
    {"stat_id": "329", "stat_name": "GIR Percentage - 125-150 yards", "category": "Approach the Green", "subcategory": "GIR"},
    {"stat_id": "330", "stat_name": "GIR Percentage - < 125 yards", "category": "Approach the Green", "subcategory": "GIR"},
    {"stat_id": "077", "stat_name": "GIR Percentage - 100-125 yards", "category": "Approach the Green", "subcategory": "GIR"},
    {"stat_id": "02332", "stat_name": "GIR Percentage - 100+ yards", "category": "Approach the Green", "subcategory": "GIR"},
    {"stat_id": "02330", "stat_name": "GIR Percentage - < 100 yards", "category": "Approach the Green", "subcategory": "GIR"},
    {"stat_id": "078", "stat_name": "GIR Percentage - 75-100 yards", "category": "Approach the Green", "subcategory": "GIR"},
    {"stat_id": "079", "stat_name": "GIR Percentage - < 75 yards", "category": "Approach the Green", "subcategory": "GIR"},
    {"stat_id": "190", "stat_name": "GIR Percentage from Fairway", "category": "Approach the Green", "subcategory": "GIR"},
    {"stat_id": "02434", "stat_name": "GIR Pct. - Fairway Bunker", "category": "Approach the Green", "subcategory": "GIR"},
    {"stat_id": "199", "stat_name": "GIR Percentage from Other than Fairway", "category": "Approach the Green", "subcategory": "GIR"},
    # Accuracy from Fairway
    {"stat_id": "02361", "stat_name": "Approaches from > 275 yards", "category": "Approach the Green", "subcategory": "Accuracy from Fairway"},
    {"stat_id": "02360", "stat_name": "Approaches from 250-275 yards", "category": "Approach the Green", "subcategory": "Accuracy from Fairway"},
    {"stat_id": "02359", "stat_name": "Approaches from 225-250 yards", "category": "Approach the Green", "subcategory": "Accuracy from Fairway"},
    {"stat_id": "02358", "stat_name": "Approaches from 200-225 yards", "category": "Approach the Green", "subcategory": "Accuracy from Fairway"},
    {"stat_id": "336", "stat_name": "Approaches from > 200 yards", "category": "Approach the Green", "subcategory": "Accuracy from Fairway"},
    {"stat_id": "337", "stat_name": "Approaches from 175-200 yards", "category": "Approach the Green", "subcategory": "Accuracy from Fairway"},
    {"stat_id": "338", "stat_name": "Approaches from 150-175 yards", "category": "Approach the Green", "subcategory": "Accuracy from Fairway"},
    {"stat_id": "339", "stat_name": "Approaches from 125-150 yards", "category": "Approach the Green", "subcategory": "Accuracy from Fairway"},
    {"stat_id": "340", "stat_name": "Approaches from 50-125 yards", "category": "Approach the Green", "subcategory": "Accuracy from Fairway"},
    {"stat_id": "074", "stat_name": "Approaches from 100-125 yards", "category": "Approach the Green", "subcategory": "Accuracy from Fairway"},
    {"stat_id": "075", "stat_name": "Approaches from 75-100 yards", "category": "Approach the Green", "subcategory": "Accuracy from Fairway"},
    {"stat_id": "076", "stat_name": "Approaches from 50-75 yards", "category": "Approach the Green", "subcategory": "Accuracy from Fairway"},
    {"stat_id": "431", "stat_name": "Fairway Proximity", "category": "Approach the Green", "subcategory": "Accuracy from Fairway"},
    # Accuracy from Rough
    {"stat_id": "437", "stat_name": "Rough Proximity", "category": "Approach the Green", "subcategory": "Accuracy from Rough"},
    {"stat_id": "432", "stat_name": "Left Rough Proximity", "category": "Approach the Green", "subcategory": "Accuracy from Rough"},
    {"stat_id": "433", "stat_name": "Right Rough Proximity", "category": "Approach the Green", "subcategory": "Accuracy from Rough"},
    {"stat_id": "02375", "stat_name": "Approaches from > 275 yards (Rgh)", "category": "Approach the Green", "subcategory": "Accuracy from Rough"},
    {"stat_id": "02374", "stat_name": "Approaches from 250-275 yards (Rgh)", "category": "Approach the Green", "subcategory": "Accuracy from Rough"},
    {"stat_id": "02373", "stat_name": "Approaches from 225-250 yards (Rgh)", "category": "Approach the Green", "subcategory": "Accuracy from Rough"},
    {"stat_id": "02372", "stat_name": "Approaches from 200-225 yards (Rgh)", "category": "Approach the Green", "subcategory": "Accuracy from Rough"},
    {"stat_id": "02371", "stat_name": "Approaches from > 100 yards (Rgh)", "category": "Approach the Green", "subcategory": "Accuracy from Rough"},
    {"stat_id": "02370", "stat_name": "Approaches from inside 100 yards (Rgh)", "category": "Approach the Green", "subcategory": "Accuracy from Rough"},
    {"stat_id": "02369", "stat_name": "Approaches from > 200 yards (Rgh)", "category": "Approach the Green", "subcategory": "Accuracy from Rough"},
    {"stat_id": "02368", "stat_name": "Approaches from 175-200 yards (Rgh)", "category": "Approach the Green", "subcategory": "Accuracy from Rough"},
    {"stat_id": "02367", "stat_name": "Approaches from 150-175 yards (Rgh)", "category": "Approach the Green", "subcategory": "Accuracy from Rough"},
    {"stat_id": "02366", "stat_name": "Approaches from 125-150 yards (Rgh)", "category": "Approach the Green", "subcategory": "Accuracy from Rough"},
    {"stat_id": "02365", "stat_name": "Approaches from 50-125 yards (Rgh)", "category": "Approach the Green", "subcategory": "Accuracy from Rough"},
    {"stat_id": "02364", "stat_name": "Approaches from 100-125 yards (Rgh)", "category": "Approach the Green", "subcategory": "Accuracy from Rough"},
    {"stat_id": "02363", "stat_name": "Approaches from 75-100 yards (Rgh)", "category": "Approach the Green", "subcategory": "Accuracy from Rough"},
    {"stat_id": "02362", "stat_name": "Approaches from 50-75 yards (Rgh)", "category": "Approach the Green", "subcategory": "Accuracy from Rough"},
    # Going for it
    {"stat_id": "419", "stat_name": "Going for the Green", "category": "Approach the Green", "subcategory": "Going for it"},
    {"stat_id": "486", "stat_name": "Going for the Green - Hit Green Pct.", "category": "Approach the Green", "subcategory": "Going for it"},
    {"stat_id": "02357", "stat_name": "Going for the Green - Birdie or Better", "category": "Approach the Green", "subcategory": "Going for it"},
    {"stat_id": "436", "stat_name": "Par 5 Going for the Green", "category": "Approach the Green", "subcategory": "Going for it"},
    {"stat_id": "02426", "stat_name": "Avg Going for it Shot Distance (yards)", "category": "Approach the Green", "subcategory": "Going for it"},
    {"stat_id": "02431", "stat_name": "Avg Distance after Going for it Shot", "category": "Approach the Green", "subcategory": "Going for it"},
    # Holeouts/Other
    {"stat_id": "350", "stat_name": "Total Hole Outs", "category": "Approach the Green", "subcategory": "Holeouts"},
    {"stat_id": "351", "stat_name": "Longest Hole Outs (in yards)", "category": "Approach the Green", "subcategory": "Holeouts"},
    {"stat_id": "02325", "stat_name": "Average Approach Shot Distance", "category": "Approach the Green", "subcategory": "Other"},
    {"stat_id": "02338", "stat_name": "Avg Approach Distance - Birdie or Better", "category": "Approach the Green", "subcategory": "Other"},
    {"stat_id": "02339", "stat_name": "Avg Approach Distance - Par", "category": "Approach the Green", "subcategory": "Other"},
    {"stat_id": "02340", "stat_name": "Avg Approach Distance - Bogey or Worse", "category": "Approach the Green", "subcategory": "Other"},
    {"stat_id": "02430", "stat_name": "Avg Distance to Hole After Tee Shot", "category": "Approach the Green", "subcategory": "Other"},
    # Around the Green
    {"stat_id": "130", "stat_name": "Scrambling", "category": "Around the Green", "subcategory": "Up and Down"},
    {"stat_id": "374", "stat_name": "Proximity to Hole (ARG)", "category": "Around the Green", "subcategory": "Accuracy"},
    {"stat_id": "111", "stat_name": "Sand Save Percentage", "category": "Around the Green", "subcategory": "Up and Down"},
    {"stat_id": "362", "stat_name": "Scrambling from the Sand", "category": "Around the Green", "subcategory": "Up and Down"},
    {"stat_id": "363", "stat_name": "Scrambling from the Rough", "category": "Around the Green", "subcategory": "Up and Down"},
    {"stat_id": "364", "stat_name": "Scrambling from the Fringe", "category": "Around the Green", "subcategory": "Up and Down"},
    {"stat_id": "365", "stat_name": "Scrambling from Other Locations", "category": "Around the Green", "subcategory": "Up and Down"},
    {"stat_id": "366", "stat_name": "Scrambling from > 30 yards", "category": "Around the Green", "subcategory": "Up and Down"},
    {"stat_id": "367", "stat_name": "Scrambling from 20-30 yards", "category": "Around the Green", "subcategory": "Up and Down"},
    {"stat_id": "368", "stat_name": "Scrambling from 10-20 yards", "category": "Around the Green", "subcategory": "Up and Down"},
    {"stat_id": "369", "stat_name": "Scrambling from < 10 yards", "category": "Around the Green", "subcategory": "Up and Down"},
    {"stat_id": "370", "stat_name": "Sand Saves from 30+ yards", "category": "Around the Green", "subcategory": "Up and Down"},
    {"stat_id": "371", "stat_name": "Sand Saves from 20-30 yards", "category": "Around the Green", "subcategory": "Up and Down"},
    {"stat_id": "372", "stat_name": "Sand Saves from 10-20 yards", "category": "Around the Green", "subcategory": "Up and Down"},
    {"stat_id": "373", "stat_name": "Sand Saves from < 10 yards", "category": "Around the Green", "subcategory": "Up and Down"},
    {"stat_id": "375", "stat_name": "Proximity to Hole from Sand", "category": "Around the Green", "subcategory": "Accuracy"},
    {"stat_id": "377", "stat_name": "Proximity to Hole from Fringe", "category": "Around the Green", "subcategory": "Accuracy"},
    {"stat_id": "376", "stat_name": "Proximity to Hole from Rough", "category": "Around the Green", "subcategory": "Accuracy"},
    {"stat_id": "378", "stat_name": "Proximity to Hole from Other Locations", "category": "Around the Green", "subcategory": "Accuracy"},
    {"stat_id": "379", "stat_name": "Proximity to Hole from 30+ yards", "category": "Around the Green", "subcategory": "Accuracy"},
    {"stat_id": "380", "stat_name": "Proximity to Hole from 20-30 yards", "category": "Around the Green", "subcategory": "Accuracy"},
    {"stat_id": "381", "stat_name": "Proximity to Hole from 10-20 yards", "category": "Around the Green", "subcategory": "Accuracy"},
    {"stat_id": "382", "stat_name": "Proximity to Hole from < 10 yards", "category": "Around the Green", "subcategory": "Accuracy"},
    {"stat_id": "481", "stat_name": "Scrambling Average Distance to Hole", "category": "Around the Green", "subcategory": "Accuracy"},
    # Around the Green Scoring
    {"stat_id": "466", "stat_name": "Scrambling > 30 yds (RTP Score)", "category": "Around the Green", "subcategory": "Scoring"},
    {"stat_id": "467", "stat_name": "Scrambling 20-30 yds (RTP Score)", "category": "Around the Green", "subcategory": "Scoring"},
    {"stat_id": "468", "stat_name": "Scrambling 10-20 yds (RTP Score)", "category": "Around the Green", "subcategory": "Scoring"},
    {"stat_id": "465", "stat_name": "Scrambling Fringe (RTP Score)", "category": "Around the Green", "subcategory": "Scoring"},
    {"stat_id": "464", "stat_name": "Scrambling Rough (RTP Score)", "category": "Around the Green", "subcategory": "Scoring"},
    # Putting Leaders
    {"stat_id": "104", "stat_name": "Putting Average", "category": "Putting", "subcategory": "Putting Averages"},
    {"stat_id": "119", "stat_name": "Putts Per Round", "category": "Putting", "subcategory": "Putts per Round"},
    {"stat_id": "413", "stat_name": "One-Putt Percentage", "category": "Putting", "subcategory": "One-Putts"},
    {"stat_id": "426", "stat_name": "3-Putt Avoidance", "category": "Putting", "subcategory": "Three-Putts"},
    {"stat_id": "484", "stat_name": "Putting Inside 10'", "category": "Putting", "subcategory": "Putting Leaders"},
    # Putting Averages
    {"stat_id": "02428", "stat_name": "Total Putting", "category": "Putting", "subcategory": "Putting Averages"},
    {"stat_id": "02439", "stat_name": "Bonus Putting", "category": "Putting", "subcategory": "Putting Averages"},
    {"stat_id": "402", "stat_name": "Overall Putting Average", "category": "Putting", "subcategory": "Putting Averages"},
    {"stat_id": "115", "stat_name": "Birdie or Better Conversion Percentage", "category": "Putting", "subcategory": "Putting Averages"},
    # Putts per Round
    {"stat_id": "393", "stat_name": "Putts per Round - Round 1", "category": "Putting", "subcategory": "Putts per Round"},
    {"stat_id": "394", "stat_name": "Putts per Round - Round 2", "category": "Putting", "subcategory": "Putts per Round"},
    {"stat_id": "395", "stat_name": "Putts per Round - Round 3", "category": "Putting", "subcategory": "Putts per Round"},
    {"stat_id": "396", "stat_name": "Putts per Round - Round 4", "category": "Putting", "subcategory": "Putts per Round"},
    {"stat_id": "397", "stat_name": "Putts per Round - Round 5", "category": "Putting", "subcategory": "Putts per Round"},
    {"stat_id": "398", "stat_name": "1-Putts per Round", "category": "Putting", "subcategory": "Putts per Round"},
    {"stat_id": "399", "stat_name": "2-Putts per Round", "category": "Putting", "subcategory": "Putts per Round"},
    {"stat_id": "400", "stat_name": "3-Putts per Round", "category": "Putting", "subcategory": "Putts per Round"},
    {"stat_id": "401", "stat_name": "3+ Putts per Round", "category": "Putting", "subcategory": "Putts per Round"},
    # One-Putts
    {"stat_id": "414", "stat_name": "One-Putt Percentage - Round 1", "category": "Putting", "subcategory": "One-Putts"},
    {"stat_id": "415", "stat_name": "One-Putt Percentage - Round 2", "category": "Putting", "subcategory": "One-Putts"},
    {"stat_id": "416", "stat_name": "One-Putt Percentage - Round 3", "category": "Putting", "subcategory": "One-Putts"},
    {"stat_id": "417", "stat_name": "One-Putt Percentage - Round 4", "category": "Putting", "subcategory": "One-Putts"},
    {"stat_id": "418", "stat_name": "One-Putt Percentage - Round 5", "category": "Putting", "subcategory": "One-Putts"},
    {"stat_id": "420", "stat_name": "Total 1 Putts - Inside 5'", "category": "Putting", "subcategory": "One-Putts"},
    {"stat_id": "421", "stat_name": "Total 1 Putts - 5-10'", "category": "Putting", "subcategory": "One-Putts"},
    {"stat_id": "422", "stat_name": "Total 1 Putts - 10-15'", "category": "Putting", "subcategory": "One-Putts"},
    {"stat_id": "423", "stat_name": "Total 1 Putts - 15-20'", "category": "Putting", "subcategory": "One-Putts"},
    {"stat_id": "424", "stat_name": "Total 1 Putts - 20-25'", "category": "Putting", "subcategory": "One-Putts"},
    {"stat_id": "425", "stat_name": "Total 1 Putts - > 25'", "category": "Putting", "subcategory": "One-Putts"},
    {"stat_id": "498", "stat_name": "Longest Putts", "category": "Putting", "subcategory": "One-Putts"},
    # Three-Putts
    {"stat_id": "427", "stat_name": "3-Putt Avoidance - Round 1", "category": "Putting", "subcategory": "Three-Putts"},
    {"stat_id": "428", "stat_name": "3-Putt Avoidance - Round 2", "category": "Putting", "subcategory": "Three-Putts"},
    {"stat_id": "429", "stat_name": "3-Putt Avoidance - Round 3", "category": "Putting", "subcategory": "Three-Putts"},
    {"stat_id": "430", "stat_name": "3-Putt Avoidance - Round 4", "category": "Putting", "subcategory": "Three-Putts"},
    {"stat_id": "440", "stat_name": "3-Putt Avoidance - Round 5", "category": "Putting", "subcategory": "Three-Putts"},
    {"stat_id": "068", "stat_name": "3-Putt Avoidance - Inside 5'", "category": "Putting", "subcategory": "Three-Putts"},
    {"stat_id": "069", "stat_name": "3-Putt Avoidance - 5-10'", "category": "Putting", "subcategory": "Three-Putts"},
    {"stat_id": "070", "stat_name": "3-Putt Avoidance - 10-15'", "category": "Putting", "subcategory": "Three-Putts"},
    {"stat_id": "145", "stat_name": "3-Putt Avoidance - 15-20'", "category": "Putting", "subcategory": "Three-Putts"},
    {"stat_id": "146", "stat_name": "3-Putt Avoidance - 20-25'", "category": "Putting", "subcategory": "Three-Putts"},
    {"stat_id": "147", "stat_name": "3-Putt Avoidance > 25'", "category": "Putting", "subcategory": "Three-Putts"},
    {"stat_id": "441", "stat_name": "Total 3 Putts - Inside 5'", "category": "Putting", "subcategory": "Three-Putts"},
    {"stat_id": "442", "stat_name": "Total 3 Putts - 5-10'", "category": "Putting", "subcategory": "Three-Putts"},
    {"stat_id": "443", "stat_name": "Total 3 Putts - 10-15'", "category": "Putting", "subcategory": "Three-Putts"},
    {"stat_id": "444", "stat_name": "Total 3 Putts - 15-20'", "category": "Putting", "subcategory": "Three-Putts"},
    {"stat_id": "445", "stat_name": "Total 3 Putts - 20-25'", "category": "Putting", "subcategory": "Three-Putts"},
    {"stat_id": "446", "stat_name": "Total 3 Putts - > 25'", "category": "Putting", "subcategory": "Three-Putts"},
    # All Putts Made by Distance
    {"stat_id": "408", "stat_name": "Putting from - > 25'", "category": "Putting", "subcategory": "All Putts Made by Dist."},
    {"stat_id": "02429", "stat_name": "Putting from - > 20'", "category": "Putting", "subcategory": "All Putts Made by Dist."},
    {"stat_id": "02328", "stat_name": "Putting from 15-25'", "category": "Putting", "subcategory": "All Putts Made by Dist."},
    {"stat_id": "407", "stat_name": "Putting from - 20-25'", "category": "Putting", "subcategory": "All Putts Made by Dist."},
    {"stat_id": "406", "stat_name": "Putting from - 15-20'", "category": "Putting", "subcategory": "All Putts Made by Dist."},
    {"stat_id": "02327", "stat_name": "Putting from 5-15'", "category": "Putting", "subcategory": "All Putts Made by Dist."},
    {"stat_id": "405", "stat_name": "Putting from - 10-15'", "category": "Putting", "subcategory": "All Putts Made by Dist."},
    {"stat_id": "404", "stat_name": "Putting from 5-10'", "category": "Putting", "subcategory": "All Putts Made by Dist."},
    {"stat_id": "02427", "stat_name": "Putting from 3-5'", "category": "Putting", "subcategory": "All Putts Made by Dist."},
    {"stat_id": "403", "stat_name": "Putting from Inside 5'", "category": "Putting", "subcategory": "All Putts Made by Dist."},
    {"stat_id": "348", "stat_name": "Putting from 10'", "category": "Putting", "subcategory": "All Putts Made by Dist."},
    {"stat_id": "347", "stat_name": "Putting from 9'", "category": "Putting", "subcategory": "All Putts Made by Dist."},
    {"stat_id": "346", "stat_name": "Putting from 8'", "category": "Putting", "subcategory": "All Putts Made by Dist."},
    {"stat_id": "345", "stat_name": "Putting from 7'", "category": "Putting", "subcategory": "All Putts Made by Dist."},
    {"stat_id": "344", "stat_name": "Putting from 6'", "category": "Putting", "subcategory": "All Putts Made by Dist."},
    {"stat_id": "343", "stat_name": "Putting from 5'", "category": "Putting", "subcategory": "All Putts Made by Dist."},
    {"stat_id": "356", "stat_name": "Putting from - > 10'", "category": "Putting", "subcategory": "All Putts Made by Dist."},
    {"stat_id": "485", "stat_name": "Putting from 4-8'", "category": "Putting", "subcategory": "All Putts Made by Dist."},
    {"stat_id": "342", "stat_name": "Putting from 4'", "category": "Putting", "subcategory": "All Putts Made by Dist."},
    {"stat_id": "341", "stat_name": "Putting from 3'", "category": "Putting", "subcategory": "All Putts Made by Dist."},
    {"stat_id": "434", "stat_name": "Putts Made Per Event Over 10'", "category": "Putting", "subcategory": "All Putts Made by Dist."},
    {"stat_id": "435", "stat_name": "Putts Made Per Event Over 20'", "category": "Putting", "subcategory": "All Putts Made by Dist."},
    # Avg. Putting Distance
    {"stat_id": "438", "stat_name": "Average Distance of Putts made", "category": "Putting", "subcategory": "Avg. Putting Dist."},
    {"stat_id": "02440", "stat_name": "Avg Distance of Birdie putts made", "category": "Putting", "subcategory": "Avg. Putting Dist."},
    {"stat_id": "02442", "stat_name": "Avg Distance of Eagle putts made", "category": "Putting", "subcategory": "Avg. Putting Dist."},
    {"stat_id": "135", "stat_name": "Putts made Distance", "category": "Putting", "subcategory": "Avg. Putting Dist."},
    {"stat_id": "349", "stat_name": "Approach Putt Performance", "category": "Putting", "subcategory": "Avg. Putting Dist."},
    {"stat_id": "409", "stat_name": "Avg Putting Distance - All 1 putts", "category": "Putting", "subcategory": "Avg. Putting Dist."},
    {"stat_id": "410", "stat_name": "Avg Putting Distance - All 2 putts", "category": "Putting", "subcategory": "Avg. Putting Dist."},
    {"stat_id": "411", "stat_name": "Avg Putting Distance - All 3 putts", "category": "Putting", "subcategory": "Avg. Putting Dist."},
    {"stat_id": "412", "stat_name": "Avg Putting Distance - All 3+ putts", "category": "Putting", "subcategory": "Avg. Putting Dist."},
    {"stat_id": "389", "stat_name": "Avg Putting Distance - GIR 1 Putts", "category": "Putting", "subcategory": "Avg. Putting Dist."},
    {"stat_id": "390", "stat_name": "Avg Putting Distance - GIR 2 Putts", "category": "Putting", "subcategory": "Avg. Putting Dist."},
    {"stat_id": "391", "stat_name": "Avg Putting Distance - GIR 3 Putts", "category": "Putting", "subcategory": "Avg. Putting Dist."},
    {"stat_id": "392", "stat_name": "Avg Putting Distance - GIR 3+ Putts", "category": "Putting", "subcategory": "Avg. Putting Dist."},
    # GIR Putts Made by Distance
    {"stat_id": "073", "stat_name": "GIR Putting Avg - > 35'", "category": "Putting", "subcategory": "GIR Putts Made by Dist."},
    {"stat_id": "072", "stat_name": "GIR Putting Avg - 30-35'", "category": "Putting", "subcategory": "GIR Putts Made by Dist."},
    {"stat_id": "071", "stat_name": "GIR Putting Avg - 25-30'", "category": "Putting", "subcategory": "GIR Putts Made by Dist."},
    {"stat_id": "388", "stat_name": "GIR Putting - > 25'", "category": "Putting", "subcategory": "GIR Putts Made by Dist."},
    {"stat_id": "387", "stat_name": "GIR Putting - 20-25'", "category": "Putting", "subcategory": "GIR Putts Made by Dist."},
    {"stat_id": "386", "stat_name": "GIR Putting - 15-20'", "category": "Putting", "subcategory": "GIR Putts Made by Dist."},
    {"stat_id": "385", "stat_name": "GIR Putting - 10-15'", "category": "Putting", "subcategory": "GIR Putts Made by Dist."},
    {"stat_id": "384", "stat_name": "GIR Putting - 5-10'", "category": "Putting", "subcategory": "GIR Putts Made by Dist."},
    {"stat_id": "383", "stat_name": "GIR Putting - Inside 5'", "category": "Putting", "subcategory": "GIR Putts Made by Dist."},
    # Scoring
    {"stat_id": "120", "stat_name": "Scoring Average (Adjusted)", "category": "Scoring", "subcategory": "Scoring Overall"},
    {"stat_id": "108", "stat_name": "Scoring Average (Actual)", "category": "Scoring", "subcategory": "Scoring Overall"},
    {"stat_id": "116", "stat_name": "Scoring Average Before Cut", "category": "Scoring", "subcategory": "Scoring Overall"},
    {"stat_id": "02417", "stat_name": "Stroke Differential Field Average", "category": "Scoring", "subcategory": "Scoring Overall"},
    {"stat_id": "299", "stat_name": "Lowest Round", "category": "Scoring", "subcategory": "Scoring Overall"},
    {"stat_id": "152", "stat_name": "Rounds in the 60s", "category": "Scoring", "subcategory": "Scoring Overall"},
    {"stat_id": "153", "stat_name": "Sub-Par Rounds", "category": "Scoring", "subcategory": "Scoring Overall"},
    {"stat_id": "156", "stat_name": "Birdie Average", "category": "Scoring", "subcategory": "Under Par Scoring"},
    {"stat_id": "107", "stat_name": "Total Birdies", "category": "Scoring", "subcategory": "Under Par Scoring"},
    {"stat_id": "155", "stat_name": "Eagles (Holes per)", "category": "Scoring", "subcategory": "Under Par Scoring"},
    {"stat_id": "106", "stat_name": "Total Eagles", "category": "Scoring", "subcategory": "Under Par Scoring"},
    {"stat_id": "105", "stat_name": "Par Breakers", "category": "Scoring", "subcategory": "Under Par Scoring"},
    {"stat_id": "160", "stat_name": "Bounce Back", "category": "Scoring", "subcategory": "Under Par Scoring"},
    {"stat_id": "02415", "stat_name": "Birdie to Bogey Ratio", "category": "Scoring", "subcategory": "Under Par Scoring"},
    {"stat_id": "112", "stat_name": "Par 3 Birdie or Better Leaders", "category": "Scoring", "subcategory": "Par 3,4,5 Scoring"},
    {"stat_id": "113", "stat_name": "Par 4 Birdie or Better Leaders", "category": "Scoring", "subcategory": "Par 3,4,5 Scoring"},
    {"stat_id": "114", "stat_name": "Par 5 Birdie or Better Leaders", "category": "Scoring", "subcategory": "Par 3,4,5 Scoring"},
    {"stat_id": "447", "stat_name": "Par 4 Eagle Leaders", "category": "Scoring", "subcategory": "Par 3,4,5 Scoring"},
    {"stat_id": "448", "stat_name": "Par 5 Eagle Leaders", "category": "Scoring", "subcategory": "Par 3,4,5 Scoring"},
    {"stat_id": "352", "stat_name": "Birdie or Better Percentage", "category": "Scoring", "subcategory": "Under Par Scoring"},
    {"stat_id": "02414", "stat_name": "Bogey Avoidance", "category": "Scoring", "subcategory": "Over Par Scoring"},
    {"stat_id": "02416", "stat_name": "Reverse Bounce Back", "category": "Scoring", "subcategory": "Over Par Scoring"},
    {"stat_id": "02419", "stat_name": "Bogey Average", "category": "Scoring", "subcategory": "Over Par Scoring"},
    # Scoring by Round
    {"stat_id": "118", "stat_name": "Final Round Scoring Average", "category": "Scoring", "subcategory": "Scoring by Round"},
    {"stat_id": "219", "stat_name": "Final Round Performance", "category": "Scoring", "subcategory": "Scoring by Round"},
    {"stat_id": "220", "stat_name": "Top 10 Final Round Performance", "category": "Scoring", "subcategory": "Scoring by Round"},
    {"stat_id": "309", "stat_name": "Top 5 Final Round Performance", "category": "Scoring", "subcategory": "Scoring by Round"},
    {"stat_id": "310", "stat_name": "11-25 Final Round Performance", "category": "Scoring", "subcategory": "Scoring by Round"},
    {"stat_id": "311", "stat_name": "25+ Final Round Performance", "category": "Scoring", "subcategory": "Scoring by Round"},
    {"stat_id": "453", "stat_name": "6-10 Final Round Performance", "category": "Scoring", "subcategory": "Scoring by Round"},
    {"stat_id": "148", "stat_name": "Round 1 Scoring Average", "category": "Scoring", "subcategory": "Scoring by Round"},
    {"stat_id": "149", "stat_name": "Round 2 Scoring Average", "category": "Scoring", "subcategory": "Scoring by Round"},
    {"stat_id": "117", "stat_name": "Round 3 Scoring Average", "category": "Scoring", "subcategory": "Scoring by Round"},
    {"stat_id": "285", "stat_name": "Round 4 Scoring Average", "category": "Scoring", "subcategory": "Scoring by Round"},
    {"stat_id": "286", "stat_name": "Round 5 Scoring Average", "category": "Scoring", "subcategory": "Scoring by Round"},
    # Par 3,4,5 Scoring
    {"stat_id": "171", "stat_name": "Par 3 Performance", "category": "Scoring", "subcategory": "Par 3,4,5 Scoring"},
    {"stat_id": "142", "stat_name": "Par 3 Scoring Average", "category": "Scoring", "subcategory": "Par 3,4,5 Scoring"},
    {"stat_id": "172", "stat_name": "Par 4 Performance", "category": "Scoring", "subcategory": "Par 3,4,5 Scoring"},
    {"stat_id": "143", "stat_name": "Par 4 Scoring Average", "category": "Scoring", "subcategory": "Par 3,4,5 Scoring"},
    {"stat_id": "173", "stat_name": "Par 5 Performance", "category": "Scoring", "subcategory": "Par 3,4,5 Scoring"},
    {"stat_id": "144", "stat_name": "Par 5 Scoring Average", "category": "Scoring", "subcategory": "Par 3,4,5 Scoring"},
    # Front/Back 9
    {"stat_id": "207", "stat_name": "Front 9 Scoring Average", "category": "Scoring", "subcategory": "Front 9 Scoring"},
    {"stat_id": "301", "stat_name": "Front 9 Lowest Round", "category": "Scoring", "subcategory": "Front 9 Scoring"},
    {"stat_id": "208", "stat_name": "Back 9 Scoring Average", "category": "Scoring", "subcategory": "Back 9 Scoring"},
    {"stat_id": "302", "stat_name": "Back 9 Lowest Round", "category": "Scoring", "subcategory": "Back 9 Scoring"},
    # Streaks
    {"stat_id": "122", "stat_name": "Consecutive Cuts", "category": "Streaks", "subcategory": "Streaks Leaders"},
    {"stat_id": "297", "stat_name": "Consecutive Fairways Hit", "category": "Streaks", "subcategory": "Off the Tee Streaks"},
    {"stat_id": "298", "stat_name": "Consecutive GIR", "category": "Streaks", "subcategory": "Approach Streaks"},
    {"stat_id": "02672", "stat_name": "Consecutive Birdies Streak", "category": "Streaks", "subcategory": "Scoring Streaks"},
    {"stat_id": "483", "stat_name": "Holes without 3-Putt", "category": "Streaks", "subcategory": "Putting Streaks"},
    {"stat_id": "475", "stat_name": "YTD Rounds in 60s Streak", "category": "Streaks", "subcategory": "Scoring Streaks"},
    {"stat_id": "137", "stat_name": "YTD Consecutive Cuts", "category": "Streaks", "subcategory": "Other Streaks"},
    {"stat_id": "296", "stat_name": "Consecutive Sand Saves", "category": "Streaks", "subcategory": "Around the Green Streaks"},
    {"stat_id": "295", "stat_name": "Best YTD 1-Putt or Better Streak", "category": "Streaks", "subcategory": "Putting Streaks"},
    {"stat_id": "294", "stat_name": "Best YTD Streak w/o a 3-Putt", "category": "Streaks", "subcategory": "Putting Streaks"},
    {"stat_id": "474", "stat_name": "Best Rounds in 60s Streak", "category": "Streaks", "subcategory": "Scoring Streaks"},
    {"stat_id": "476", "stat_name": "Best Sub-Par Rounds Streak", "category": "Streaks", "subcategory": "Scoring Streaks"},
    {"stat_id": "477", "stat_name": "YTD Sub-Par Rounds Streak", "category": "Streaks", "subcategory": "Scoring Streaks"},
    {"stat_id": "150", "stat_name": "Current Par or Better Streak", "category": "Streaks", "subcategory": "Scoring Streaks"},
    {"stat_id": "482", "stat_name": "YTD Par or Better Streak", "category": "Streaks", "subcategory": "Scoring Streaks"},
    {"stat_id": "449", "stat_name": "Consecutive Par 3 Birdies", "category": "Streaks", "subcategory": "Scoring Streaks"},
    {"stat_id": "450", "stat_name": "Consecutive Par 4 Birdies", "category": "Streaks", "subcategory": "Scoring Streaks"},
    {"stat_id": "451", "stat_name": "Consecutive Par 5 Birdies", "category": "Streaks", "subcategory": "Scoring Streaks"},
    {"stat_id": "452", "stat_name": "Consecutive Holes Below Par", "category": "Streaks", "subcategory": "Scoring Streaks"},
    {"stat_id": "02673", "stat_name": "Consecutive Birdies/Eagles streak", "category": "Streaks", "subcategory": "Scoring Streaks"},
    # Money/Finishes
    {"stat_id": "109", "stat_name": "Official Money", "category": "Money/Finishes", "subcategory": "Money"},
    {"stat_id": "110", "stat_name": "Career Money Leaders", "category": "Money/Finishes", "subcategory": "Money"},
    {"stat_id": "014", "stat_name": "Career Earnings", "category": "Money/Finishes", "subcategory": "Money"},
    {"stat_id": "139", "stat_name": "Non-member Earnings", "category": "Money/Finishes", "subcategory": "Money"},
    {"stat_id": "02677", "stat_name": "Non-Member Off+WGC Earnings", "category": "Money/Finishes", "subcategory": "Money"},
    {"stat_id": "02444", "stat_name": "Money Leaders - Fall Series", "category": "Money/Finishes", "subcategory": "Money"},
    {"stat_id": "02396", "stat_name": "FedExCup Bonus Money", "category": "Money/Finishes", "subcategory": "Money"},
    {"stat_id": "154", "stat_name": "Money per Event Leaders", "category": "Money/Finishes", "subcategory": "Money"},
    {"stat_id": "194", "stat_name": "Total Money (Official and Unofficial)", "category": "Money/Finishes", "subcategory": "Money"},
    {"stat_id": "02337", "stat_name": "Percentage of Available Purse Won", "category": "Money/Finishes", "subcategory": "Money"},
    {"stat_id": "02447", "stat_name": "Percentage of potential money won", "category": "Money/Finishes", "subcategory": "Money"},
    {"stat_id": "138", "stat_name": "Top 10 Finishes", "category": "Money/Finishes", "subcategory": "Finishes"},
    {"stat_id": "300", "stat_name": "Victory Leaders", "category": "Money/Finishes", "subcategory": "Finishes"},
    # Points/Rankings
    {"stat_id": "02671", "stat_name": "FedExCup Standings", "category": "Points/Rankings", "subcategory": "Points"},
    {"stat_id": "02698", "stat_name": "FedExCup Fall Points", "category": "Points/Rankings", "subcategory": "Points"},
    {"stat_id": "02562", "stat_name": "FedExCup Points per Event Leaders", "category": "Points/Rankings", "subcategory": "Points"},
    {"stat_id": "02448", "stat_name": "% of Potential Pts won - FedExCup Regular Season", "category": "Points/Rankings", "subcategory": "Points"},
    {"stat_id": "02398", "stat_name": "FedExCup Season Points for Non-Members", "category": "Points/Rankings", "subcategory": "Points"},
    {"stat_id": "131", "stat_name": "Ryder Cup Points", "category": "Points/Rankings", "subcategory": "Points"},
    {"stat_id": "140", "stat_name": "Presidents Cup Points (United States)", "category": "Points/Rankings", "subcategory": "Points"},
    {"stat_id": "187", "stat_name": "Presidents Cup Points (International)", "category": "Points/Rankings", "subcategory": "Points"},
    {"stat_id": "02667", "stat_name": "Non-WGC FedExCup Season Points for Non-Members", "category": "Points/Rankings", "subcategory": "Points"},
    {"stat_id": "132", "stat_name": "PGA Championship Points", "category": "Points/Rankings", "subcategory": "Points"},
    {"stat_id": "127", "stat_name": "All-Around Ranking", "category": "Points/Rankings", "subcategory": "Rankings"},
    {"stat_id": "186", "stat_name": "Official World Golf Ranking", "category": "Points/Rankings", "subcategory": "Rankings"},
    {"stat_id": "085", "stat_name": "Power Rating", "category": "Points/Rankings", "subcategory": "Rankings"},
    {"stat_id": "086", "stat_name": "Accuracy Rating", "category": "Points/Rankings", "subcategory": "Rankings"},
    {"stat_id": "087", "stat_name": "Short Game Rating", "category": "Points/Rankings", "subcategory": "Rankings"},
    {"stat_id": "088", "stat_name": "Putting Rating", "category": "Points/Rankings", "subcategory": "Rankings"},
    {"stat_id": "02346", "stat_name": "Scoring Rating", "category": "Points/Rankings", "subcategory": "Rankings"},
    {"stat_id": "02347", "stat_name": "Last 5 Events - Power", "category": "Points/Rankings", "subcategory": "Rankings"},
    {"stat_id": "02348", "stat_name": "Last 5 Events - Accuracy", "category": "Points/Rankings", "subcategory": "Rankings"},
    {"stat_id": "02349", "stat_name": "Last 5 Events - Short Game", "category": "Points/Rankings", "subcategory": "Rankings"},
    {"stat_id": "02350", "stat_name": "Last 5 Events - Putting", "category": "Points/Rankings", "subcategory": "Rankings"},
    {"stat_id": "02351", "stat_name": "Last 5 Events - Scoring", "category": "Points/Rankings", "subcategory": "Rankings"},
    {"stat_id": "02352", "stat_name": "Last 15 Events - Power", "category": "Points/Rankings", "subcategory": "Rankings"},
    {"stat_id": "02353", "stat_name": "Last 15 Events - Accuracy", "category": "Points/Rankings", "subcategory": "Rankings"},
    {"stat_id": "02354", "stat_name": "Last 15 Events - Short Game", "category": "Points/Rankings", "subcategory": "Rankings"},
    {"stat_id": "02355", "stat_name": "Last 15 Events - Putting", "category": "Points/Rankings", "subcategory": "Rankings"},
    {"stat_id": "02356", "stat_name": "Last 15 Events - Scoring", "category": "Points/Rankings", "subcategory": "Rankings"},
])
